ceste <-
structure(list(V1 = c("BREZOVICA", "VRHNIKA", "LIVOLD", "LJ(VIE)", 
"AC BREZOVICA", "BREZOVICA", "VRHNIKA", "STARI TRG"), V2 = c("VRHNIKA", 
"LOGATEC", "BREZOVICA", "AC BREZOVICA", "BREZOVICA", "VRHNIKA", 
"LOGATEC", "BREZOVICA"), V3 = c("green", "green", "red", "orange", 
"orange", "orange", "orange", "orange"), V4 = c(FALSE, FALSE, 
TRUE, TRUE, FALSE, FALSE, FALSE, TRUE), V5 = c(12424, 8279, 16230, 
2741, 1400, 11761, 9525, 8464), V6 = c(130, 130, 50, 90, 90, 
90, 90, 90), V7 = c(1, 1, 0.0164, 0.2672, 0.504, 0.1814, 0.1416, 
0.0167)), row.names = c("BREZOVICA_VRHNIKA_AC", "VRHNIKA_LOGATEC_AC", 
"LIVOLD_BREZOVICA_R1", "LJ(VIE)_AC BREZOVICA_R2", "AC BREZOVICA_BREZOVICA_R2", 
"BREZOVICA_VRHNIKA_R2", "VRHNIKA_LOGATEC_R2", "STARI TRG_BREZOVICA_R3"
), class = "data.frame")
koor <-
structure(list(V1 = c(167.34, 654.5, 898.08, 811.72, 851.58, 
441.83, 475.65), V2 = c(811.71, 425.4, 478.69, 783.17, 162.79, 
893.54, 143.76)), row.names = c("LJ(VIE)", "AC BREZOVICA", "BREZOVICA", 
"VRHNIKA", "LIVOLD", "LOGATEC", "STARI TRG"), class = "data.frame")
povezave <-
list(`LJ(VIE)_AC BREZOVICA_R2` = "AC BREZOVICA_BREZOVICA_R2", 
    LIVOLD_BREZOVICA_R1 = c("BREZOVICA_VRHNIKA_AC", "BREZOVICA_VRHNIKA_R2"
    ), `AC BREZOVICA_BREZOVICA_R2` = c("BREZOVICA_VRHNIKA_AC", 
    "BREZOVICA_VRHNIKA_R2"), `STARI TRG_BREZOVICA_R3` = c("BREZOVICA_VRHNIKA_AC", 
    "BREZOVICA_VRHNIKA_R2"), BREZOVICA_VRHNIKA_AC = c("VRHNIKA_LOGATEC_AC", 
    "VRHNIKA_LOGATEC_R2"), BREZOVICA_VRHNIKA_R2 = c("VRHNIKA_LOGATEC_AC", 
    "VRHNIKA_LOGATEC_R2"))
verjetnosti <-
list(`LJ(VIE)_AC BREZOVICA_R2` = 1, LIVOLD_BREZOVICA_R1 = c(0.893, 
0.107), `AC BREZOVICA_BREZOVICA_R2` = c(0.893, 0.107), `STARI TRG_BREZOVICA_R3` = c(0.893, 
0.107), BREZOVICA_VRHNIKA_AC = c(0.777, 0.083), BREZOVICA_VRHNIKA_R2 = c(0.777, 
0.083))
semaforji <-
list(VRHNIKA = structure(list(BREZOVICA_VRHNIKA_AC__VRHNIKA_LOGATEC_AC = c(FALSE, 
TRUE), BREZOVICA_VRHNIKA_AC__VRHNIKA_LOGATEC_R2 = c(TRUE, FALSE
), BREZOVICA_VRHNIKA_R2__VRHNIKA_LOGATEC_AC = c(TRUE, FALSE), 
    BREZOVICA_VRHNIKA_R2__VRHNIKA_LOGATEC_R2 = c(FALSE, TRUE)), row.names = 1:2, class = "data.frame"), 
    BREZOVICA = structure(list(LIVOLD_BREZOVICA_R1__BREZOVICA_VRHNIKA_AC = c(FALSE, 
    TRUE), LIVOLD_BREZOVICA_R1__BREZOVICA_VRHNIKA_R2 = c(TRUE, 
    FALSE), `AC BREZOVICA_BREZOVICA_R2__BREZOVICA_VRHNIKA_AC` = c(TRUE, 
    FALSE), `AC BREZOVICA_BREZOVICA_R2__BREZOVICA_VRHNIKA_R2` = c(FALSE, 
    TRUE), `STARI TRG_BREZOVICA_R3__BREZOVICA_VRHNIKA_AC` = c(TRUE, 
    FALSE), `STARI TRG_BREZOVICA_R3__BREZOVICA_VRHNIKA_R2` = c(FALSE, 
    TRUE)), row.names = 1:2, class = "data.frame"))
